### ISSUE TITLE
Scanning on Android 8.1 does not show ble devices

### ISSUE THREAD

**Issue by varunpandey0502** [googlesamples/android-BluetoothLeGatt#57]
After building the app and deploying on Android 8.1 device, I am unable to discover ble devices after clicking on the "Scan" button.

**Comment by varunpandey0502** [comment]
After debugging, found that location permission was required to be set. Now it's working fine.

**Comment by ahmedvvaqar** [comment]
but i am also facing this issue even after turning on location services.what can i do now ?
